version: "3.7"
services:
  dev:
    container_name: fastapi-test
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    volumes:
      - type: bind
        source: .
        target: /srv
        consistency: cached
    env_file:
      - .env
    restart: always
    ports:
      - 8081:8081
